// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: aperture/policy/sync/v1/classifier.proto

package syncv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ClassifierWrapper with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ClassifierWrapper) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClassifierWrapper with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClassifierWrapperMultiError, or nil if none found.
func (m *ClassifierWrapper) ValidateAll() error {
	return m.validate(true)
}

func (m *ClassifierWrapper) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetClassifierAttributes()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClassifierWrapperValidationError{
					field:  "ClassifierAttributes",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClassifierWrapperValidationError{
					field:  "ClassifierAttributes",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetClassifierAttributes()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClassifierWrapperValidationError{
				field:  "ClassifierAttributes",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetClassifier()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClassifierWrapperValidationError{
					field:  "Classifier",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClassifierWrapperValidationError{
					field:  "Classifier",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetClassifier()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClassifierWrapperValidationError{
				field:  "Classifier",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ClassifierWrapperMultiError(errors)
	}

	return nil
}

// ClassifierWrapperMultiError is an error wrapping multiple validation errors
// returned by ClassifierWrapper.ValidateAll() if the designated constraints
// aren't met.
type ClassifierWrapperMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClassifierWrapperMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClassifierWrapperMultiError) AllErrors() []error { return m }

// ClassifierWrapperValidationError is the validation error returned by
// ClassifierWrapper.Validate if the designated constraints aren't met.
type ClassifierWrapperValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClassifierWrapperValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClassifierWrapperValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClassifierWrapperValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClassifierWrapperValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClassifierWrapperValidationError) ErrorName() string {
	return "ClassifierWrapperValidationError"
}

// Error satisfies the builtin error interface
func (e ClassifierWrapperValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClassifierWrapper.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClassifierWrapperValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClassifierWrapperValidationError{}

// Validate checks the field values on ClassifierAttributes with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClassifierAttributes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClassifierAttributes with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClassifierAttributesMultiError, or nil if none found.
func (m *ClassifierAttributes) ValidateAll() error {
	return m.validate(true)
}

func (m *ClassifierAttributes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PolicyName

	// no validation rules for PolicyHash

	// no validation rules for ClassifierIndex

	if len(errors) > 0 {
		return ClassifierAttributesMultiError(errors)
	}

	return nil
}

// ClassifierAttributesMultiError is an error wrapping multiple validation
// errors returned by ClassifierAttributes.ValidateAll() if the designated
// constraints aren't met.
type ClassifierAttributesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClassifierAttributesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClassifierAttributesMultiError) AllErrors() []error { return m }

// ClassifierAttributesValidationError is the validation error returned by
// ClassifierAttributes.Validate if the designated constraints aren't met.
type ClassifierAttributesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClassifierAttributesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClassifierAttributesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClassifierAttributesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClassifierAttributesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClassifierAttributesValidationError) ErrorName() string {
	return "ClassifierAttributesValidationError"
}

// Error satisfies the builtin error interface
func (e ClassifierAttributesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClassifierAttributes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClassifierAttributesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClassifierAttributesValidationError{}
